/*
 * This source file was generated by the Gradle 'init' task
 */
package org.bugmakers404.tools;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class ApplicationTest {

  @Test
  void appHasAGreeting() {
    Application classUnderTest = new Application();
    assertNotNull(classUnderTest.toString(), "app should have a greeting");
  }
}
