/*
 * This source file was generated by the Gradle 'init' task
 */
package org.bugmakers404.tools;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

  @Test
  void appHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull(classUnderTest.toString(), "app should have a greeting");
  }
}
